// example: export const ADD = "ADD";
// employee
export const EMPLOYEELIST = "EMPLOYEELIST"
export const ADDEMPLOYEE = "ADDEMPLOYEE"
export const ACCOUNTSTATUS = "ACCOUNTSTATUS"
export const UPDATEEMPLOYEE = "UPDATEEMPLOYEE"
export const SEARCHEMPLOYEE = "SEARCHEMPLOYEE"

// parkinglot

export const PARKINGLOTLIST = "PARKINGLOTLIST"
export const ADDPARKINGLOT = "ADDPARKINGLOT"
export const MODIFYPARKINGLOT = "MODIFYPARKINGLOT"

// order
export const ORDERSLIST = "ORDERSLIST"
export const PATCHORDER = "PATCHORDER"


//parkinglot in dashboard
export const PARKINGLOTLISTINDASHBOARD="PARKINGLOTLISTINDASHBOARD"
